# Generated by Django 4.2.13 on 2024-05-27 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rank',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
