# Generated by Django 4.2.13 on 2024-05-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0002_hotel_city_hotel_country_hotel_name_hotel_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('serial_number', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('price_for_night', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_list', to='booking_site.hotel')),
            ],
        ),
    ]
