# Generated by Django 4.2.13 on 2024-06-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0007_reservation_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_list', to='booking_site.hotel'),
        ),
    ]
